// <auto-generated />
using System;
using BeachBuddy.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeachBuddy.Migrations
{
    [DbContext(typeof(BeachBuddyContext))]
    [Migration("20200602011542_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeachBuddy.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("KanJamWinCount")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("StarCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1783ec3d-e689-4249-9e08-7ea71590eb27"),
                            FirstName = "Andrew",
                            KanJamWinCount = 0,
                            LastName = "Marshall",
                            StarCount = 0
                        },
                        new
                        {
                            Id = new Guid("6966b63f-de4e-4854-aaf1-27d3ea963097"),
                            FirstName = "Lena",
                            KanJamWinCount = 0,
                            LastName = "Brottman",
                            StarCount = 0
                        },
                        new
                        {
                            Id = new Guid("be21613c-249c-4703-8571-e7a371133c91"),
                            FirstName = "Clayton",
                            KanJamWinCount = 0,
                            LastName = "French",
                            StarCount = 0
                        },
                        new
                        {
                            Id = new Guid("1b301c75-dbb9-436e-996d-9bff2cf0d5a3"),
                            FirstName = "Erica",
                            KanJamWinCount = 0,
                            LastName = "Moore",
                            StarCount = 0
                        },
                        new
                        {
                            Id = new Guid("0ddeea52-cf23-4e91-9b65-fce283aa3a11"),
                            FirstName = "Stephen",
                            KanJamWinCount = 0,
                            LastName = "Elkourie",
                            StarCount = 0
                        },
                        new
                        {
                            Id = new Guid("bfe1bb10-a683-4408-8bdb-d771248c695f"),
                            FirstName = "Lacey",
                            KanJamWinCount = 0,
                            LastName = "Gibbs",
                            StarCount = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
